# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: Set .NET Version
    inputs:
      version: 7.0.x
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      arguments: "--configuration Release"
  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: "--configuration Release --verbosity normal"
    
